### ISSUE TITLE
SweetAlert looks complete window

### ISSUE THREAD

**Issue by orangecoding** [limonte/sweetalert2#144]
Version: 3.1.0
Frameworks used: React 15.0.1

Problem:
Using SweetAlert 3.0.2 -> no problems
Using SweetAlert 3.1.0 (and above) -> problem occurred

If I am using sweetalert 3.1.0 and above, after I've opened an alert, the whole screen is locked.
See fiddle.
https://jsfiddle.net/bfq9hg2h/2/

By the way, it was kind of hard to find the version it broke.. Something like git bisect for npm would be awesome oO

**Comment by Tonkpils** [comment]
@orangecoding you can always clone the repo and checkout specific tags and `git bisect` that locally. 

In any case, I'm not sure what the issue is. You mention the whole screen is locked but I just tried jsfiddle you provided and it works just fine. It opens a new tab when I click on the first link then I can open the SweetAlert go through the flog and click the link again just fine. 

Could you please elaborate the steps you're taking and the browser your using?

**Comment by orangecoding** [comment]
That is strange. seems to work now. Had the problem with latest chrome and safari. Will test this again on monday..

**Comment by limonte** [comment]
Thank you @Tonkpils for filling me in on this issue. I can't reproduce this bug either (Chrome latest).

**Comment by orangecoding** [comment]
@limonte @Tonkpils Cannot be reproduced. I swear the problem was there. In my own code as well as within the fiddle. Anyways. It seems to be gone now. Therefor I'll close this issue. Thanks.
