### ISSUE TITLE
sweetalert2.min.js:1 Uncaught TypeError: e.substr is not a function

### ISSUE THREAD

**Issue by dbraddillon** [limonte/sweetalert2#159]
I know this is pretty vague but it's all I've got right now.  I switched to sweetalert2 yesterday and most everything is working, windows still come up, but I get this error repeatedly in Chrome.  In IE it's even more annoying but the same error.  Not sure where to start with it. No errors on loading the library only upon use does the exception come up.

**Comment by Tonkpils** [comment]
Seems like an issue on this line.  https://github.com/limonte/sweetalert2/blob/08b93526eeb13bdfaa237846163996de5b27d4e0/src/utils/utils.js#L26 

and caused by one of the lines that call colorForLuminance here https://github.com/limonte/sweetalert2/blob/08b93526eeb13bdfaa237846163996de5b27d4e0/src/sweetalert2.js#L446-L471

Would you happen to have different values for `buttonsStyling`, `confirmButtonColor`, `cancelButtonColor`

**Comment by dbraddillon** [comment]
Yes!  I'm wrapping the library and trying to read some bootstrap styles/colors and apply them dynamically to the sw settings.  I'm changing the confirm and cancel button colors directly.  Is there a correct way to do this or a better example I can follow?  It's working as far as changing the colors so I thought it was fine.

**Comment by Tonkpils** [comment]
You could disable buttonsStyling altogether if you're doing that yourself

**Comment by dbraddillon** [comment]
I think I'm good now, I am not getting the error, and I'm getting my styling, it's not as nice and neat as it was before with using the defaults but I'll tinker with it later.  For now it works and can be refactored at a later time.  Thanks for the help!

**Comment by Tonkpils** [comment]
No problem, feel free to re-open this issue if you run into something!
