### ISSUE TITLE
Cancel button calls resolve

### ISSUE THREAD

**Issue by AmitMY** [limonte/sweetalert2#175]
In the 'Are you sure?' examples, the cancel button should call `reject`, not `resolve`
(Proper promise syntax, I think)

**Comment by limonte** [comment]
Yes, it's proper Promise but for historical reasons confirm and cancel buttons are calling `resolve(isConfirm)`

`isConfirm` will be:

- `true` for "Confirm"-button
- `false` for "Cancel"-button
- `undefined` for Esc press, close button or outside click

**Comment by AmitMY** [comment]
Well, history should not determinate the future in my opinion, Really think you should consider changing it

**Comment by limonte** [comment]
How should we handle the Esc button press, close button or outside click according to your suggestion?

**Comment by AmitMY** [comment]
In my opinion, because all do the same action, they should do `reject()`
That way, if there is a promise in the SWAL, and it rejects, it will normally `reject(error)`, such that you can handle by checking `if(error)`
And if not, and the promise sends reject() it means just 'close' - no nead for error handling.

This removes the check `if(isConfirm)`, and uses the build in promise rejection

What do you think? Where am I logically failing?

**Comment by FourStacks** [comment]
I've just run into this very problem when upgrading from swal1 to swal2 (by the way - big thanks to @limonte for taking the project on).  Haven't had a chance to dig into the internals of swal2 properly but @AmitMY's suggestion makes good sense to me.  I guess this change might break BC a bit though it certainly feels more like the right way to handle the modal cancellation.

**Comment by limonte** [comment]
Thank you @AmitMY for standing for you point, I probably have to agree with you and make this breaking change :)

Please give your opinion about this structure:

```js

swal({
  ...
}).then(function() {
  // handle confirm
}, function(dismiss) {
  // dismiss can be "cancel" | "close" | "outside"
});
```

cc @samturrell @Tonkpils @jdcrensh

**Comment by AmitMY** [comment]
Yep, this is a good structure in my opinion.
Thanks a lot for listening, I know breaking stuff is not your priority :)

It is good, because if you have a promise with `reject`, like an AJAX request, the rejection sends 3 or 4 parameters, so you can always know what is the source of an action.

Cheers

**Comment by samturrell** [comment]
Looks good to me

On Sun, 12 Jun 2016 at 12:31 pm Limon Monte

<
mailto:Limon Monte <notifications@github.com>
> wrote:

Thank you
https://github.com/AmitMY
for standing for you point, I probably have to agree with you and make this breaking change :)

Please give your opinion about this structure:

swal

({

...

}).

then

(

function

() {

// handle confirm

},

function

(

dismiss

) {

// dismiss can be "cancel" | "close" | "outside"

});

cc
https://github.com/samturrell https://github.com/Tonkpils https://github.com/jdcrensh

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/limonte/sweetalert2/issues/175#issuecomment-225427650
, or
https://github.com/notifications/unsubscribe/AFpOjApovhXaF-2w6Vj53dXBSx9Ivcgyks5qK-4ugaJpZM4Izm-K
.

https://github.com/limonte/sweetalert2/issues/175#issuecomment-225427650

**Comment by jdcrensh** [comment]
I like it 👍

**Comment by limonte** [comment]
Here we go [v4.0.0](https://github.com/limonte/sweetalert2/releases/tag/v4.0.0)

**Comment by AmitMY** [comment]
Thanks!

**Comment by FourStacks** [comment]
Awesome, thanks @limonte (and @AmitMY for opening the ticket)!
