### ISSUE TITLE
Type select data from ajax

### ISSUE THREAD

**Issue by masadi** [limonte/sweetalert2#182]
Here my code:

`$.ajax({

			url: '<?php echo site_url($nama_group.'/pembayaran/ambil_kategori'); ?>',

			type: 'post',

			data: {category_id:category_id},

			success: function(response){

				var data = $.parseJSON(response);

			swal({

				title: 'Pilih Periode Pembayaran',

				input: 'select',

				inputOptions: {

					// how to display var data here?

				},`

Thanks

**Comment by sunnywalker** [comment]
Is there a way to grab select options via AJAX per this request? I've tried `inputOptions: $.getJSON()` since the `$.getJSON()` method implements the Promise interface (which the swal2 examples infer), but then my select only shows methods. Do I need to create a new Deferred object and work from that? Any guidance would be helpful.
![screen shot 2017-01-13 at 4 15 00 pm](https://cloud.githubusercontent.com/assets/187270/21951516/ac2843ca-d9ab-11e6-95d0-3f0dde0ff283.png)
