### ISSUE TITLE
Custom directive not working inside the modal pop up

### ISSUE THREAD

**Issue by sbnighut** [limonte/sweetalert2#208]
https://plnkr.co/edit/EoGCOH2ydMuvg7QJuEx5?p=preview

As seen from the plnkr link, the custom directive "alert" works outside the pop up but when I use the same directive through the "swal" function (Note: html: <alert></alert>), the pop up does not reflect the directive contents

**Comment by samturrell** [comment]
Hi @sbnighut,

Due to the nature of javascript frameworks such as angular, they don't register new events being added directly into the DOM as sweetalert2 does. What you will have to do is some kind of compilation event after firing the sweetalert that registers it in the dom with Angular. 

This thread seems to be what you're after, you'll just have to replace `$('body').append()` with `$('alert').replace()`: http://stackoverflow.com/a/20059469/1375989

**Comment by sbnighut** [comment]
Thanks Sam, I had to call the $compile function in order to resolve my directive's HTML into pop up. 
I ran the following code after calling swal():
$compile(angular.element('clone-directive'))($scope.$new());
