### ISSUE TITLE
Registering events inside Swal HTML

### ISSUE THREAD

**Issue by masiamj** [limonte/sweetalert2#231]
I've spent some time on this now, but am stuck. Not sure if this is intended functionality, but I can't register a clickListener for a button declared inside the "html" property of the Swal.

Anybody else struggled and achieved this?

**Comment by limonte** [comment]
If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then submit it to [StackOverflow](http://stackoverflow.com/questions/ask) instead of GitHub, and make sure you added [`sweetalert`](http://stackoverflow.com/questions/tagged/sweetalert) tag to the question.
