### ISSUE TITLE
IE, issue with fade-out animation

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#239]
**[[JSFIDDLE]](https://jsfiddle.net/ad3quksn/27/)**

There's an issue with the hiding animation in IE (notice the short blink in the end of the fade out animation):

![111](https://cloud.githubusercontent.com/assets/6059356/17464868/777884de-5ce0-11e6-8c11-3e1e0890190b.gif)

**Comment by birjolaxew** [comment]
Unable to reproduce in IE11 (Windows 7) and Edge (Windows 10 VM). Which version/OS are you running?

![edge](https://cloud.githubusercontent.com/assets/4542461/17465733/1a48702e-5d00-11e6-968c-5874815c0bc7.gif)

**Comment by limonte** [comment]
Win10/IE11. 

I just created the new Win10/IE11 VM and yes, I can confirm this issue. The worst part if this issue is that it's happenings in 50% of cases, i.e. if I'm closing modal 10 times, 5 will be ok and other 5 will be with this strange animation issue.

**Comment by birjolaxew** [comment]
Can't test on Win10/IE11 since [Microsoft's VM's](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) don't have it.

Went back and test on Win7/IE11 and Win10/Edge again, still unable to reproduce (25 tries on each browser). Can't really help much :/

Might be an issue with the animation ending a tiny bit before the modal is hidden? Perhaps try messing with the animations [fill mode](https://developer.mozilla.org/en/docs/Web/CSS/animation-fill-mode)?
