### ISSUE TITLE
preConfirm with inputValidator

### ISSUE THREAD

**Issue by zenichanin** [limonte/sweetalert2#247]
Is it possible to use `inputValidator` with `preConfirm`?  Looking at source code, it looks like `inputValidator` only runs if there's `input` fields inserted using the default method but not if I'm inserting them using `preConfirm`.

I suppose it would be nice to have a `postConfirm` in this case?

**Comment by limonte** [comment]
> but not if I'm inserting them using preConfirm

`preConfirm` is not supposed for inserting input fields.

**Comment by zenichanin** [comment]
Sorry I meant if I'm getting the input values via `preConfirm` but inserting them via `html` property.  

Basically I'm trying to add validation to the last example shown here:

[https://limonte.github.io/sweetalert2/](url)

**Comment by limonte** [comment]
Aha, sorry. The answer for your question is: `inputValidator` is working for swal2 input fields only (`input` parameter).

Inputs in the `html` parameter are totally custom and `inputValidator` can't do magic and validate whatever you provides in custom HTML code.

**Comment by zenichanin** [comment]
Got it.  Thanks!  Just wanted to confirm that was the case so I can build my own validation for it.

**Comment by Herz3h** [comment]
This is an old issue, but I have the same problem. I have a swal with custom html, and inputValidator is indeed not called.

So where is validation supposed to happen in this case ??

Thanks

**Comment by gverni** [comment]
Hi @Herz3h can you provide a sample of your code using [these instructions](https://github.com/sweetalert2/sweetalert2/wiki/How-to-provide-live-example-for-issue) so we can debug it?

**Comment by Herz3h** [comment]
I don't think it's a bug per say. As I'm not specifying input option to swal2, and according to what's being said above, inputValidator is not called in that case. 

Anyway I have ended up adding my validation to preConfirm() like so : 
```javascript
swal({
    title: 'Choisir un dossier',
    html: `<div class="form-group" style="margin-top:15px">
                        <div class="input-group input-group-sm col-md-10 col-md-offset-1">
                            <select class="select2 form-control dossiers-list">
                                <option></option>
                            </select>
                        </div>
                    </div>`,
    showCancelButton: true,
    cancelButtonText: "Annuler",
    onOpen: function() {
        $('.dossiers-list').select2({
            data: dossiers,
            placeholder: 'Selectionner un dossier',
            allowClear: true,
            templateSelection: function(data, container) {
                // Add custom attributes to the <option> tag for the selected option
                $(data.element).attr('data-folder-name', data.folderName);
                return data.text;
            }
        });
    },
    preConfirm: (value) => {
        console.log(value)
        let selected = $('select.dossiers-list').find(':selected').attr('data-folder-name') !== undefined;

        if (!selected) {
            swal.showValidationError('Vous devez choisir un dossier');
        }

        return $('select.dossiers-list').find(':selected').data('folder-name')
    },
}).then((result) => {
    console.log(result);
    if (typeof result.dismiss !== 'undefined')
        return;
}):
 ```
Not sure if this is the way to go, but it seems to not execute the last then block. (This was the case, until I added `swal.showValidationError()`)

**Comment by gverni** [comment]
Hi @Herz3h i'm a bit confused. I tried your code [here](https://glitter-peony.glitch.me/) and it works for me both with and without `showValidationError()`. Note that I removed the `onOpen` implementation to decrease the complexity of the sample. 

Can you explain better what's the expected behavior and what doesn't work for you?

**Comment by Herz3h** [comment]
Uh the original issue is that if I remove the preConfirm above and replace with say:

```javascript
inputValidator: function(value)
{
    return new Promise((resolve) => {
        resolve('Error');
    });
}
```

The inputValidator is not called. I think it'd be good that this function gets called so the user can validate custom html aswell instead of having to use preConfirm.

As for the second problem I had while trying to fix the first one. It's that I didn't use showValidationError(). So even though the user input could be wrong, the last then block gets called, which is not what I want since input is invalid: 

```javascript
.then((result) => { console.log(result); if (typeof result.dismiss !== 'undefined') return; }):
```

But adding showValidationError() prevents that last then block from being called which is expected behavior.

I'm not sure if this is clear, but I had two related issues. All regarding user input validation.

**Comment by gverni** [comment]
> The inputValidator is not called. I think it'd be good that this function gets called so the user can validate custom html aswell instead of having to use preConfirm.

As explained originally, the `inputValidator` is only used when the input is defined through the `input` property of swal. And it couldn't be otherwise: if the input to the swal is defined through `html`, then swal doesn't know which of the element(s) is to be considered an input. 

> So even though the user input could be wrong, the last then block gets called, which is not what I want since input is invalid:

The only (and the correct) way to stop the swal promise to resolve (i.e. to execute the `then` block), is to use the ` showValidationError()`. So this is the expected behavior. Please also note that this latter is deprecated and you should use showValidationMessage()` instead. 

Does it answers your doubts?

**Comment by Herz3h** [comment]
Yup thank you !
