### ISSUE TITLE
top:50%, margin-top: - half   ->  Half is not well calculated when adding an image

### ISSUE THREAD

**Issue by kenvernaillenvub** [limonte/sweetalert2#248]
top:50%, margin-top: -half   ->  Half is not well calculated when adding an image.
This puts the modal way too low on the screen.

**Comment by birjolaxew** [comment]
Reproducable. [JSFiddle example.](https://jsfiddle.net/6y6ebfzu/) [Setting `imageHeight` fixes it.](https://jsfiddle.net/6y6ebfzu/1/)

Happens because remote image height isn't available until the image has loaded. To fix it, we should add a `"load"` event listener and recalculate the height at that point.

**Comment by limonte** [comment]
@birjolaxew exactly! could you handle this improvement?

**Comment by birjolaxew** [comment]
@limonte Sure. It'll take a few hours before I have access to my PC though.

**Comment by limonte** [comment]
@birjolaxew Great! No hurry, feel free to send the PR at any time.

**Comment by kenvernaillenvub** [comment]
The same thing happens when the title text is split up into 2 parts on small screens.

**Comment by birjolaxew** [comment]
@kenvernaillenvub Could you post a JSFiddle? [I can't seem to reproduce.](https://jsfiddle.net/2c2m0sx6/)

**Comment by kenvernaillenvub** [comment]
nvm, it was the image ;) (I was wrong)

**Comment by limonte** [comment]
Fixed in [v4.1.7](https://github.com/limonte/sweetalert2/releases/tag/v4.1.7)
