### ISSUE TITLE
onOpen/onClose not working with chained modals

### ISSUE THREAD

**Issue by mineralwassermedium** [limonte/sweetalert2#257]
Hello,

when I try this: 

    var steps = [
    {
        title: 'Step 1',
        text: 'Chaining swal2 modals is easy',
        onOpen: function() { console.log('test'); }
    },
        'Step 2',
        'Step 3'
    ];

nothing happens. 
Is this supposed to be like that? Is it a bug? Or am I doing something wrong?

Cheers

**Comment by limonte** [comment]
all works just fine https://jsfiddle.net/0pbgaka4/1/

**Comment by birjolaxew** [comment]
@mineralwassermedium If you want the `onOpen` callback to be bound to each of the queued alerts, you'll have to put it on each of them - the values you give to `.queue` are simply passed to `swal()` one after another, so the options don't carry over. It's simply an easier way to queue alerts rather than using

    swal( ... )
        .then(function(){
            return swal( ... );
        }).then(function(){
            return swal( ... );
        }).then( ... )
