### ISSUE TITLE
full size of content without scrolling

### ISSUE THREAD

**Issue by baum1234** [limonte/sweetalert2#272]
Is it possible to have the full content size without scrolling inside of the alert however scrolling the whole page?
In some content cases (mobile and a lot content) it's not clear if there is more content e.g. the buttons.

**Comment by limonte** [comment]
Nice request @baum1234 but, unfortunately, I think it's not possible to implement what you are asking with the current implementation of swal2.

Probably, it will be useful in those rare cases to add styles for the mobile scrollbar to be more visible for users.

**Comment by baum1234** [comment]
I don't think it's a rare case. I just saw that a lot of smartphones would get the scrolling inside.
Here an example that would effect all iPhones + iPhone SE till iPhone 6
![image](https://cloud.githubusercontent.com/assets/16719494/18232600/16c2e8ce-72d3-11e6-8673-f4aa290314b1.png)

**Comment by Silvester20** [comment]
I have the same problem as @baum1234 , so a fix will be nice!

**Comment by birjolaxew** [comment]
This isn't particularly easy to fix, and might be breaking for some configurations (so should bump the semver major). While we're doing this, we should also take the chance to re-visit #225 (I'm personally a fan of removing scroll on body).

The basic idea behind one way to fix this is that we change the `.swal2-modal`'s `position: fixed` to `position: absolute`, and position it manually. This does have one major downside: users can scroll away until the modal is no longer visible. I personally see this as too big for it to be useful. [JSFiddle example.](https://jsfiddle.net/tvbs5npy/)

Next, slightly more complicated fix: have a container with scroll on it. Unfortunately, this means that we might have *two* scrollbars if the body has overflow (one from the body, one from the container). [JSFiddle example.](https://jsfiddle.net/zmcL6xsp/)

Finally, the way more complicated fix: put `overflow-y: hidden` on the `<body>` when the modal is visible. This requires adding some padding to the body so the content doesn't move when we remove the scrollbar (see [Bootstrap's modal implementation](https://github.com/twbs/bootstrap/blob/master/js/modal.js#L259-L286)). It'll also require some restructuring of our DOM element, since the backdrop would otherwise cover the scrollbar. [JSFiddle example.](https://jsfiddle.net/ewzqnt51/)

The last example will definitely be a breaking change, since we modify DOM structure, and will also greatly increase the complexity of our show-modal logic.

**Comment by limonte** [comment]
wow @birjolaxew you did the amazing job by researching on this issue and answering it.

**Comment by limonte** [comment]
Done in [v5.0.0](https://github.com/limonte/sweetalert2/releases/tag/v5.0.0).

Many thanks to @birjolaxew!

**Comment by baum1234** [comment]
Thank you, but how can I use it now? There is no description for the new feature.

**Comment by limonte** [comment]
@baum1234 there's nothing that you should change in your code, just update swal2 to latest and you're done :)

**Comment by baum1234** [comment]
I create a new test file with this code and the new swal2:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

	<link rel="stylesheet" href="./sweetalert2.min.css" media="screen">

	<script src="./sweetalert2.min.js"></script>
</head>
	<body>
		<script>
			swal({
				title: 'Error!',
				text: 'Do you want to continue\r\nDo you want to continue\r\nDo you want to continue\r\nDo you want to continue',
				type: 'error',
				confirmButtonText: 'Cool'
			})
		</script>
	</body>
</html>
```

And this is how it looks like now:
![image](https://cloud.githubusercontent.com/assets/16719494/18709422/6654c45e-8000-11e6-84d5-19a356708405.png)

I guess it should now be scrollable outside the modal window, right?

**Comment by limonte** [comment]
Are you sure you're using the latest version - v5.0.5?

**Comment by baum1234** [comment]
Yes. Just to get sure I just downloaded the latest version and replaced it with the older ones and cleared the cache too.

**Comment by birjolaxew** [comment]
Probably #299. Discussion should go there instead.

**Comment by limonte** [comment]
@baum1234 could you please upgrade to [v5.0.7](https://github.com/limonte/sweetalert2/releases/tag/v5.0.7) and test once again?
