### ISSUE TITLE
Redirect before confirm

### ISSUE THREAD

**Issue by vicainelli** [limonte/sweetalert2#312]
I'm trying use this solution #27, but is not working for me, anyone can help me with this?

```javascript
$(document).ready(function() {
  swal({
    title: 'Good job!',
    text: 'You clicked the button!',
    type: 'success'
  }, function(isConfirm){
    document.location.href = 'http://www.goole.com/';
    return false;
  });
});
```

**Comment by acupajoe** [comment]
If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
