### ISSUE TITLE
onOpen and onClose should provide the modal DOM element as the first argument

### ISSUE THREAD

**Issue by pomartel** [limonte/sweetalert2#351]
It seems that since version 6.0, the `onOpen` and `onClose` callbacks no longer return the modal as the first argument. It is now `undefined`.

https://jsfiddle.net/ad3quksn/55/

**Comment by birjolaxew** [comment]
Seems to be from [a botched ES6 rewrite](https://github.com/limonte/sweetalert2/commit/de3f67936d48a4f9f4b52903f6516170cbc898a8#diff-1957cf081e6f36591195eae3cf092341R254) which turned `onComplete.call(this, modal)` into `onComplete(undefined, modal)`.

Note that it would be perfectly fine to re-introduce the `.call`, since [arrow functions simply ignore `this`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Invoked_through_call_or_apply), but I have chosen not to in my fix since it would give users access to our internal functions.

**Comment by limonte** [comment]
Done in [v6.1.1] (https://github.com/limonte/sweetalert2/releases/tag/v6.1.1), thanks for reporting!
