### ISSUE TITLE
How to tell developers that the original plugin is outdated?

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#388]
I'm looking how better is swal2 from the original swal. Despite this, judging by questions on StackOverflow, I see that developers still using the original plugin more often.

I'm wondering if there any nice ways to tell developers about this plugin, so they will use the supported plugin and submit their issues/PRs and get the actual support and responses.

The current situation is weird, community submits PRs [into the void](https://github.com/t4t5/sweetalert/pulls), it seems that there won't be any response ever.

**Comment by birjolaxew** [comment]
Best bet is to contact @t4t5 and ask him to add a link to this in his readme, if he doesn't want to maintain his library. Judging by his [commit history](https://github.com/t4t5/sweetalert/commits/master) though, his lib *does* appear to be maintained (although not as actively as this), so he might not be interested in doing so.

It should also be mentioned that this lib isn't a direct upgrade from his lib - swal2 introduces reliance on promises, for instance, and breaking API changes, so it isn't as simple as pointing people here; some might prefer using the old swap over this one.

**Comment by toverux** [comment]
I agree with @birjolaxew, commits are still rare on the original projects, and sweetalert2 is actively developed and received lots of bug fixes and features. I don't know what are the feels or t4t5 about its own library, since it's its most successful work on GitHub, probably he just lacked of time and the project is gone a bit out of hand with all the PRs and issues.

But ihmo and technically speaking, yes, swal2 could make a good, official successor, of swal. And I'm also very sad to see all the people continuing to post issues and PR on swal, whilst those would be welcome here.

Two ideas thrown in the air:
 - If swal "1" stays online and maintened as it is now, at least add a little note leading to this project in the readme, as an alternative ;
 - Moving the project into a more neutral zone, like a "SweetAlert" organization where we could have repos for teh lib, examples, [or even bootstrap variant](https://github.com/lipis/bootstrap-sweetalert) who knows. A bit scifi-esque atm but if we could get the projects "merged" one day, it would probably be the best.

**Comment by acupajoe** [comment]
If you're looking just for more exposure on the plugin some quick searching shows that the highest ranked javascript notification/alert libraries have their own domain names rather than piggybacking off of github. 

There are also a couple of review sites and bloggers that post about the best notification libraries that show up on the top searches: 
- [ourcodeworld](http://ourcodeworld.com/articles/read/52/top-10-best-notification-libraries-and-plugins-for-javascript-and-jquery)
- [jqueryhouse](http://jqueryhouse.com/best-jquery-notification-plugins/)
- [techslides](http://techslides.com/50-plugins-for-alerts-and-notifications)

So in terms of garnering interest from new developers, I would vote reaching out to existing mediums. Although the askers on stackoverflow do seem to have a very positive reaction to the introduction of sweetalert2.

I agree with @toverux that t4t5 prolly won't be fond of suggesting a different library or marking his as 'depreciated'. It is still, although infrequently, still developed on. 

Another aspect that should be looked into is a detailed migration guide from `sweetalert` to `sweetalert2` to combat the breaking changes mentioned by @birjolaxew. I can work on writing one if that's something of interest.

**Comment by malcolmocean** [comment]
So I was like "gah, sweetalert has all of these issues and isn't being maintained and PRs are being ignored. *Surely* there's got to be a best replacement! ...but there are over 2000 forks!

Fortunately sweetalert2 was result # 8 when I googled "sweet alert focus". But what would have been *awesome* is a link to sweetalert2 on [this sweetalert issue thread](https://github.com/t4t5/sweetalert/issues/391), which is actually talking about the bug I had (or at least a related bug). This could even be reasonable to do without having already fixed the bug yourself, because @EduardJS commented "I will make a PR tomorrow with a fix for this." and it would be helpful for him to know that sweetalert isn't really accepting PRs while sweetalert2 is!

**Comment by EduardJS** [comment]
@malcolmocean Hei Malcolm. To be honest, I already knew **swal2** is out. I made that PR just for the people who don't want to boggle with moving towards the new version, which has it's differences.

I already wrote in another issue, that people can go towards the new version. It's just that google still points most of them to this one :)

Regards

**Comment by malcolmocean** [comment]
Well that seems worth mentioning on threads like those in general! That way we'll get more critical mass moving over here :smile:

**Comment by jdussouillez** [comment]
I discovered SweetAlert "1" thanks to the browser extension [Wappalyzer](https://wappalyzer.com/) while I was on a website with beautiful alerts. On the [Wappalyzer SweetAlert page](https://wappalyzer.com/applications/sweetalert) I found the project website (the link is now dead) and used it.
Swal2 was already out for a few months but I didn't know that. I used swal1 for a while until I found a bug and discovered this project.

Swal2 detection is not implemented by Wappalyzer and I think it would be nice to do it. People could discover and use swal2 first, instead of swal1.
I know this project is "only" a fork but it's becoming more and more different from the original.

I made a quick search on how the module detection works. Apparently you juste have to add a new configuration in the extension application list. [Here's the swal1 configuration](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L7193)

**Comment by taxpayer** [comment]
@jdussouillez, I use and follow the SweetAlert project since the original developer launched it. And I also tracked the project from a fork that is called "SweetAlert2" since then. This project, Swal2, is not "only" a fork since a long time ago. For some moment in the past, the developer even tried to take back the development of the original project, but Swal2 was (is) years (lines of code) ahead.

Now the "official" project *is* Swal2, I don't think there's question about it. @limonte (and now the other guys that help) took a dead project and pumped it up. Many new features, many bug corrections, this is the **living** project.

Of course there are many sites that still point to the original project. That was the way I also found it. But I can bet that the first search for a bug correction that does not exist in the original project will link the searcher to the Swal2 project. Then, the person, after searching and reading more about it, will clearly undersatnd which project s/he must follow.

**Comment by limonte** [comment]
> I discovered SweetAlert "1" thanks to the browser extension Wappalyzer while I was on a website with beautiful alerts. On the Wappalyzer SweetAlert page I found the project website (the link is now dead) and used it.
>
>Swal2 was already out for a few months but I didn't know that. I used swal1 for a while until I found a bug and discovered this project.
>
>Swal2 detection is not implemented by Wappalyzer and I think it would be nice to do it. People could discover and use swal2 first, instead of swal1. 

This is done: 
![](https://i.imgur.com/RkR7Q7H.png)

https://wappalyzer.com/applications/sweetalert2
