### ISSUE TITLE
Help with variables, array show on the alert.

### ISSUE THREAD

**Issue by John1987vlc** [limonte/sweetalert2#389]
Hi, I was using alert(var[1]) to show names or numbers save in a array or in normal alert(var) now I was change to use sweetalert like I was use before alert() but I can't show variables. It is posible?

**Comment by acupajoe** [comment]
@John1987vlc Thanks for your interest in sweetalert2! Be aware that our issue section is for *bugs* only. 

The short answer is that yes this is possible and the [examples](https://limonte.github.io/sweetalert2/) show how to do that. For a more specific answer please ask this on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.
