### ISSUE TITLE
The .close() doesn't call the close callback function

### ISSUE THREAD

**Issue by SasSam** [limonte/sweetalert2#395]
Hi,

If I call the `.close()` (or` .closeModal()`) method, it doesn't fire the defined close callback function, however if I click on the gray overlay or press ESC, it's firing.

I use it like this:

```
var openFn = function () {
  ...
};

var closeFn = function () {
  ...
};

swal({
    html: currentCardContent,
    showConfirmButton: false,
    showCancelButton: false,
    buttonsStyling: false,
    showCloseButton: true,
    onOpen: openFn,
    onClose: closeFn
}).catch(swal.noop);

```

**Comment by toverux** [comment]
Reading the source code, it seems intentional, only in the sense that it's not a bug. Is that the behaviour we want @limonte? I think that closeModal should read modalParameters.onClose directly and in all cases instead of receiving it as a parameter.

However, some people may want to close the modal programatically, without having the callback called, to differentiate between user and script close requests. Changing the current behavior is therefore a breaking change.

**Comment by SasSam** [comment]
@toverux Yes, it does make sense. I call the `close()` with a parameter and it works.

**Comment by limonte** [comment]
The current behavior is intentional, I personally want to keep it.

As @toverux mentioned, users should be able to close a modal without calling a close callback function.

If you want to close a modal programmatically using `swal.close()`, just pass the function to it:

```js
swal.close(myCloseCallback)
```
