### ISSUE TITLE
Definable height

### ISSUE THREAD

**Issue by SasSam** [limonte/sweetalert2#397]
Hi,

If the height would be changeable/definable in the options (like the width) that would be great. Or an option for "full screen" (eg. 90-95% width and height) mode.

**Comment by toverux** [comment]
Hi,

Since Web isn't geometry, it's more rare that we want to set a height other than "auto", than we do for the width.
Another symptom of that, is that it's also more complicated technically since CSS pre-flexbox is bad at vertical layouting.

My point is that, I would suggest you to keep the automatic sizing of the modal's height. It will adapt to your content. But if you have, for example, a large text to display in the modal and want to have a scrollable area, then just use the `html` option of SweetAlert2, and give it a fixed height:

```
<p style="height: 200px">
    My very long text, lorem ipsum dolor sit amet.
</p>
```

Is that enough for you? Or do you see any real and frequent use cases requiring implemeting a `height` option?
