### ISSUE TITLE
sweetalert2 not supported RequireJSAMD with ES6Promise (IE)?

### ISSUE THREAD

**Issue by ghuarcayam** [limonte/sweetalert2#416]
I am trying to configure sweetalert2 with ES6Promise but I have the following error

Promise is not defined

Requirejs:
Shim {
    Swal: {deps: ['ES6Promise']}
}

--- any ideas?

**Comment by toverux** [comment]
I don't know what type of configuration this is, but I can recommend you three things:
 - Don't use a polyfill/shim, if you don't have to support old browsers and IE, v.11 included
 - Use a library like [bluebird](http://bluebirdjs.com/docs/getting-started.html), that can polyfill Promise and bring extra features
 - Use a high-quality, "general-purpose" polyfill like [core-js](https://github.com/zloirock/core-js)

Since the problem you have is related to your build configuration (and only that), we can't help you further to fix it. Sorry!

**Comment by nmiddendorff** [comment]
Credit to @toverux .
Adding core-js is the fix for IE. I tried adding the es6-promise but the button clicks still did nothing. After adding core-js it worked as expected.
