### ISSUE TITLE
Incomplete installation instructions

### ISSUE THREAD

**Issue by danidee10** [limonte/sweetalert2#422]
First of all i'll like to say good work keeping `sweetalert` alive. I've been using the old sweetalert library via cdn. i can't really remember how i came across your fork.

I don't know if i'm missing something but the [installation instructions](https://limonte.github.io/sweetalert2/) seem to be incomplete. After importing the module with

`import { default as swal } from 'sweetalert2'`. 

It's not documented that you also have to import/require the css files so all the styles and buttons can be loaded also. In my case with `npm`. It was a simple.

`import './node_modules/sweetalert2/dist/sweetalert2.css'`

Ideally i feel it would make more sense if i just imported `swal` and internally the css has already been imported. because i don't think anyone would want to use sweetalert2 without the buttons and the css.

**Comment by toverux** [comment]
I agree, we really should document the styles part.

Don't forget that `import 'sweetalert2/dist/sweetalert2.css';` is specific to module bundlers (for example Webpack) so we can't just put *"import the CSS file using an import statement"* on the README, or we may confuse a lot of users. I already see those issues such as *"I've imported the CSS with `import` but it says syntax error, please fix your syntax yo"*.
The fact is, it's difficult to document every build systems on earth, because something like `<link rel="stylesheet" type="text/css" href="node_modules/sweetalert2/etc" media="screen" />` is also a solution for others.

I'm really in favor of embedding the styles into the library, that would make the things much simpler and we could benefit of tree-shaking on the styles too (once the library has the right structure for this).

**Comment by danidee10** [comment]
@toverux but at least we should have a section, that says

"don't forget to import the stylesheet `sweetalert2.css`" or something similar

or maybe a FAQ section to answer the question of "sweetalert2 styles are not working"

My point is there should be something in the docs that gives a pointer to the css file, even though it's not bundler specific.

**Comment by toverux** [comment]
You're right. I'll add a note on the README, and maybe document that a little further in a wiki entry.

At medium term, I'll see what I can do to include the styles in the JavaScript. A simple approach would be to bundle the CSS build into the sources, and inject it at runtime by creating a <style> element. A better approach would be to play around with those JS-based, CSS-like styling solutions we can find these days.

**Comment by danidee10** [comment]
@toverux okay. Please let me know when these changes have been integrated. :+1:

**Comment by limonte** [comment]
@toverux ping :)

**Comment by danidee10** [comment]
@limonte pong! 😄 . 

I've seen the update.

Cheers!

**Comment by limonte** [comment]
I think this issue isn't resolved yet

**Comment by danidee10** [comment]
@limonte @toverux woops! i guess i saw what i wanted to see (thought i saw something about importing CSS in the `README`). My bad!

**Comment by andreich1980** [comment]
@danidee10 why wouldn't you make a PR?

**Comment by limonte** [comment]
Good news, everyone!

Thanks to @samturrell now it's possible to import all-in-one JS + (S)CSS file:

```js
import swal from 'sweetalert2/src/sweetalert2.all.js'
```

or minified version:

```js
import swal from 'sweetalert2/dist/sweetalert2.all.min.js'
```

**Comment by limonte** [comment]
Minified version will be the default entry point one in the upcoming major release, that means that in near future 

```js
import swal from 'sweetalert2
```

will import the all-in-one version.

So @toverux, no need to do any updates in the documentation.

**Comment by Ayberkone** [comment]
@danidee10 dude u rly saved my life, I spent 45 mins on this.
