### ISSUE TITLE
Disable confirming the modal with enter/space key?

### ISSUE THREAD

**Issue by sgsellmann-miovision** [limonte/sweetalert2#423]
I would like to disable the confirm action of the modal from `enter`/`space` keys. What is the best way to do this?

Our use case is: users are performing an action by holding down the `space` key which can trigger a modal. This modal is then immediately dismissed before the user can even see it. This did not occur in the original version of sweetalert (we've just upgraded to sweetalert2.)

I see there is a `allowEscapeKey` property but, for exampe, no `allowEnterKey`. 

Thanks!

**Comment by ChazyTheBest** [comment]
That happens because of the focus the button element has. If you remove the focus, then the keys won't trigger the click event. For that you can use `blur()`.

```javascript
document.getElementByTagName('button')[0].blur();
```

For a temporal solution should work ok.

Something inside sweetalert2 must be triggering the focus on the element. I'm also interested in knowing how to disable it.

**Comment by sgsellmann-miovision** [comment]
Ah yes, good idea. Thanks.

**Comment by limonte** [comment]
Fixed in [v6.4.1](https://github.com/limonte/sweetalert2/releases/tag/v6.4.1) :tada:

**Comment by sgsellmann-miovision** [comment]
Confirmed and working as expected. Great job, thanks!

**Comment by narender2031** [comment]
Hy
I am still facing issue in allowEscapeKey Please help me
