### ISSUE TITLE
What's the difference between sweetalert and sweetalert2?

### ISSUE THREAD

**Issue by tonyxiao** [limonte/sweetalert2#46]
I can't seem to find any docs about it. What was your motivation for the fork and how is this different from the original?

**Comment by limonte** [comment]
http://stackoverflow.com/a/27842854/1331425

**Comment by Systho** [comment]
Please add a note about this difference in Readme

**Comment by limonte** [comment]
@Systho done, thx for your suggestion.

**Comment by tonyxiao** [comment]
As of right now though limonte:master is 82 commits ahead, 103 commits behind t4t5:master. Do you have any plan to merge?

**Comment by limonte** [comment]
Nope. The original plugin still has many PRs and issues without any feedback. Last activity [was on Oct 21, 2015](https://github.com/t4t5/sweetalert/commits/master) so I think it's better to keep both plugins.

**Comment by tonyxiao** [comment]
Sorry by merge I meant pulling changes from `sweetalert` into `sweetalert2` master, not merging upstream.

**Comment by limonte** [comment]
I don't think so. Original swal plugin became more complex in structure than it should be. Code simplicity allows other swal2 users to contribute easily.

**Comment by seyfer** [comment]
The original one looks active now
https://github.com/t4t5/sweetalert

and they have 3x more stars. Reasons mentioned on SO still actual? @limonte what do you think?

**Comment by abuassar** [comment]
now that sweetalert released version 2.0 , they closed the gap with sweetalert2 by alot!
I think they took hints from this project

https://sweetalert.js.org/guides/#upgrading-from-1x

**Comment by cdsmith** [comment]
It is extremely confusing that there are now two incompatible libraries called "sweetalert v2.0" and "sweetalert2".  At the very least, it would be nice to make it clear in the documentation for this project what the relationship is.

**Comment by NickWoodhams** [comment]
Based on a little research it appears the owner of Sweetalert V1 is contributing to Sweetalert2, so I'd say it's official. I was just worried about going with a version ripped off from the original creator.. now I'm it's settled. 

(t4t5 under contributors https://github.com/sweetalert2/sweetalert2/graphs/contributors)

**Comment by toverux** [comment]
@NickWoodhams, well, to be fair, no he's not [contributing]. Not directly. Those contributions come from the first repo, because @limonte did the thing correctly and did not reset the Git history when he cloned the previous repo.

But it's not stolen. That's open source, the license was compatible and we did point to the old repo, _completely_ abandoned at the time.

Nowadays the codebase is completely different and has nothing in common with the original one, except for the icons maybe. It's an original work.
So, feel free to use whatever version you like and please be assured that we're not thieves :)
