### ISSUE TITLE
Encapsulate this sweet sweetalert in a sweet webcomponent.

### ISSUE THREAD

**Issue by gilberto-torrezan** [limonte/sweetalert2#495]
Please also create a webcomponent (using Polymer, for instance) for this sweet library, so I can "html import" it in my projects ;-)

**Comment by toverux** [comment]
Excellent suggestion, was thinking about this yesterday!

For the people who find this issue and are interested in an Angular 2+ specific implementation, check my project here : [ngsweetalert2](https://github.com/toverux/ngsweetalert2).

**Comment by limonte** [comment]
Vue.js is so beautiful: http://vuetips.com/vue-web-components

**Comment by karlos545** [comment]
@limonte I saw a post from you a while ago regarding this. You said it was over engineering and closed the issue, do you still have the same opinion? 
ref: https://github.com/limonte/sweetalert2/issues/163

**Comment by limonte** [comment]
Sure, sweetalert2 is dependency-free vanillaJS plugin and I don't plan to change it. 

A Polymer/Vue.js/whatnot component will be another project(s) in separated repository(ies).

**Comment by AlexSwensen** [comment]
Agreed. I currently use SWAL2 in an Angular 1+ app, and we find it rather simple to use and modify to our needs. We have written our own wrapper that functions as middleware/service between our app and SWAL2 and increases its effectiveness and flexibility. Adding framework specific patterns/uses/implementations into this library both limit its audience, and add complexity. 

@gilberto-torrezan: It should be trivial to wrap SWAL2 in whatever you need for your own use case.

**Comment by mattbrunetti** [comment]
Same, we're using it with Angular 1 and we have a pretty thin wrapper around it that makes it an AngularJS service. 

It adds some AngularJS integration, so if a `controller` is passed in through options, the swal2 modal is compiled as a template with the instantiated controller on it's scope. This way we can support the "multiple inputs" scenario as exemplified in the [examples](https://limonte.github.io/sweetalert2/), but with AngularJS instead of jQuery.

It would be nice to collaborate on these kinds of further enhancements, but I think there's really not that much to collaborate on?

**Comment by mattbrunetti** [comment]
Since we expect this module to be wrapped, I think there is one change that would make it a bit cleaner. 

There are some methods that aren't defined until the first popup get's called, so I have this at the bottom of my wrapper

```

  // Copy all methods over, including ones that won't be defined at this time
  const methodNames = [ 'isVisible', 'setDefaults', 'resetDefaults', 'close', 'enableButtons', 'getTitle', 'getContent', 'getImage', 'getConfirmButton', 'getCancelButton', 'disableButtons', 'enableConfirmButton', 'disableConfirmButton', 'showLoading', 'hideLoading', 'clickConfirm', 'clickCancel', 'showValidationError', 'resetValidationError', 'getInput', 'disableInput', 'enableInput', 'queue', 'getQueueStep', 'insertQueueStep', 'deleteQueueStep', 'getProgressSteps', 'setProgressSteps', 'showProgressSteps', 'hideProgressSteps' ]
  methodNames.forEach(methodName => {
    alert[ methodName ] = (...args) => swal[ methodName ].apply(swal, args)
  })

  return alert
```

If all of these methods were defined when the module is loaded, I could use some less-brittle more-final code like this

```
Object.keys(swal)
    .filter(key => typeof swal[ key ] === 'function')
    .forEach(key => {
      alert[ key ] = swal[ key ].bind(swal)
    })

return alert
```

**Comment by mattbrunetti** [comment]
@limonte Does my last comment, in regards to making this package easier and cleaner to wrap, make sense? Do you see this as a valuable change?

**Comment by stephan-v** [comment]
Please keep this as lightweight and clean as possible.

**Comment by gilberto-torrezan** [comment]
One goal of having this encapsulated in an webcomponent is to have it avaiable on webcomponents.org.

In theory you don't need to use other frameworks (other than the native APIs) to be able to encapsulate it, but it would be way harder I guess.

I'm ok with it being a separate project as long as it stays always up-to-date with the main project.

**Comment by limonte** [comment]
@gilberto-torrezan https://www.webcomponents.org/element/limonte/sweetalert2-polymer :tada:
