### ISSUE TITLE
swal.showLoading is not a function

### ISSUE THREAD

**Issue by suhrab** [limonte/sweetalert2#518]
swal.showLoading not working.
Uncaught TypeError: swal.showLoading is not a function
https://jsfiddle.net/dcby5df3/1/

But works like this:
https://jsfiddle.net/qn6btnf7/4/

**Comment by limonte** [comment]
Thanks for reporting @suhrab !

What is the expected behavior of the first jsfiddle?

**Comment by acupajoe** [comment]
@limonte The desired behavior would be: if a dialog is not open when `swal.showLoading()` is called, create a new dialog, open it, and display the loading icon. 

I wouldn't consider this to be a bug, as this has been defined as showing the loading indicator on an _existing_ and _open_ dialog.

@suhrab can you make a case for otherwise?

**Comment by suhrab** [comment]
> What is the expected behavior of the first jsfiddle?
The desired behavior would be: if a dialog is not open when swal.showLoading() is called, create a new dialog, open it, and display the loading icon.
**Exactly!**

**Comment by limonte** [comment]
Makes sense, I'll handle this.

**Comment by limonte** [comment]
Fixed in [v6.6.4](https://github.com/limonte/sweetalert2/releases/tag/v6.6.4).

Thanks for reporting!
