### ISSUE TITLE
.catch(swal.noop)

### ISSUE THREAD

**Issue by shabuninil** [limonte/sweetalert2#540]
Tell me, is not it better to suppress this error by default?
It turns out that almost all calls to messages require the presence of such a function. This complicates the work and makes the code less beautiful. The more that in almost all of your examples this function is not.

**Comment by mattbrunetti** [comment]
@shabuninil Set the `useRejections` option to false

**Comment by limonte** [comment]
Привет Игорь,

The previous comment is correct and `useRejections` will be the default setting in the upcoming major release. That means that `.catch(swal.noop)` won't be needed anymore (big thanks to @mattbrunetti for suggesting and implementing this change :beers:)

Till then we can't help you because we can't change the way JS promises are working.

I will notify you here about the next major release, thanks for using SweetAlert2!

**Comment by shabuninil** [comment]
Yes, thank you very much. I'll wait for updates.

**Comment by limonte** [comment]
It's not needed anymore to use `.catch(swal.noop)` :tada: 

Please read about some breaking changes in https://github.com/limonte/sweetalert2/releases/tag/v7.0.0
