### ISSUE TITLE
How to pass angular selector as html option

### ISSUE THREAD

**Issue by rszczypka** [limonte/sweetalert2#587]
I'm using latest angular (4.3.2) and would like to use my component (it's selector is `app-ask-for-email`) as the content of my modal e.g.
```
private askForEmailModalOptions: SweetAlertOptions = {
    type: 'info',
    html: `<app-ask-for-email></app-ask-form-email>`,
    showConfirmButton: false,
    allowOutsideClick: true,
    showCancelButton: false,
    showCloseButton: true,
    allowEscapeKey: true
  };
```

But the template is not compiled. Is there a way to make it work?

**Comment by limonte** [comment]
This question doesn't actually related to SweetAlert2. You should ask it in the Angular community, e.g. https://stackoverflow.com/questions/tagged/angularjs

**Comment by limonte** [comment]
Also, take a look on the Angular 2+ wrapper for SweetAlert2: https://github.com/toverux/ngsweetalert2 - it's great!

**Comment by rszczypka** [comment]
Thanks, https://github.com/toverux/ngsweetalert2 is great but it doesn't show me how to do the stuff I want to achieve. I already posted on stackoverflow: https://stackoverflow.com/questions/45500265/how-to-pass-angular-selector-as-html-option-of-sweetalert2

**Comment by toverux** [comment]
Well, amusing, someone just asked me the same question: https://github.com/toverux/ngsweetalert2/issues/16

That's not possible right now, but I'm considering adding it since it's a real use case.

And remember, `html` is just an option that takes an HTML string. That has just nothing to do with Angular template syntax. You HAVE to use some kind of <ng-template> or transclusion.
