### ISSUE TITLE
Error while using laravel webpack.mix babel

### ISSUE THREAD

**Issue by andreich1980** [limonte/sweetalert2#647]
When I do this everything works fine.
```
import swal from 'sweetalert2/dist/sweetalert2.all.min.js'
```

But when I do this
```
import swal from 'sweetalert2/src/sweetalert2.all.js'
```
then `yarn prod` I get an error
```
\js\app.es6.js from UglifyJs
Unexpected token: operator (>) [./node_modules/sweetalert2/src/utils/classes.js:3,0][\js\app.es6.js:19281,24]
```
`yarn dev` doesn't show the error, everything compiles well.

My `webpack.mix.js`
```
if (process.env.NODE_ENV == 'production') {
    mix.js([
        'resources/assets/js/app.js',
    ], 'public/js/app.es6.js')
        .extract(['jquery', 'bootstrap-sass', 'vue', 'bootstrap-datepicker'])
        .babel('public/js/app.es6.js', 'public/js/app.js')
    ;
}
else {
    mix.js([
            'resources/assets/js/app.js',
        ], 'public/js/app.js')
        .extract(['jquery', 'bootstrap-sass', 'vue', 'bootstrap-datepicker']);
}
```

**Comment by toverux** [comment]
The file in dist/ is transpiled down to ES 5. However classes.js in src/ is ES 2015+. Apparently the UglifyJS version distributed with Laravel Mix is outdated.

You can either:

- Use the dist/ version, safer
- Configure your Mix config to transpile ES 2015 through Babel
- Maybe update Mix or something, so it handles ES 2015 (and if your application targets this language version)

As this is not a SweetAlert-specific issue and since we already provide a ready-to-run build in dist/, I suggest you to get help on StackOverflow :)

**Comment by andreich1980** [comment]
Thank you.
