### ISSUE TITLE
Feature request: Add an option in Swal options to hide backdrop

### ISSUE THREAD

**Issue by kgrvr** [limonte/sweetalert2#680]
In current scenario, there is no option of removing backdrop (overlay) from the alert background.
Add a new flag to remove backdrop.

Secondly, If user wants to remove backdrop, the other area apart from alert is not clickable. 
So if user removes backdrop, the other area must be clickable.

**Comment by toverux** [comment]
The backdrop is the container of the modal, so it requires to change how SweetAlert2 uses the DOM, it's not a trivial change.
But... @acupajoe, I presume you've implemented that in the toasts branch? It would allow to implement that along with toasts.

**Comment by limonte** [comment]
SweetAlert2 is the replacement for modal popups. Modal windows should have backdrop and trap focus by definition.

Read more about modal and nonmodal dialog windows: https://www.nngroup.com/articles/modal-nonmodal-dialog/ 

You can always make the backdrop transparent though: https://jsfiddle.net/ad3quksn/160/

**Comment by kgrvr** [comment]
So there's no way to make the other are clickable?

**Comment by limonte** [comment]
> So there's no way to make the other are clickable?

**Definition**: A modal dialog is a dialog that appears on top of the main content and moves the system into a special mode requiring user interaction. This dialog disables the main content until the user explicitly interacts with the modal dialog.

**Comment by limonte** [comment]
I just changed my mind :upside_down_face: 

Thanks @kgrvr for proposing this feature. Now, since we have a positioning functionality starting from https://github.com/limonte/sweetalert2/releases/tag/v6.11.0 use-cases like these should be possible: 

![](https://i.imgur.com/hPHqCdh.jpg)

![image](https://user-images.githubusercontent.com/6059356/32113156-25cdb754-bb48-11e7-8fa9-70da663c3c8e.png)

**Comment by kgrvr** [comment]
@limonte Yup. These use cases are also possible. I was actually trying to implement toast notifications using swal, and from there I found out that you people are going to implement it in near future, and from there I got to this. Happy to hear that though. :)

**Comment by toverux** [comment]
I've been thinking about that for a while: SweetAlert2 needs a (partial yet non-trivial) rewrite to handle multiple instances. The limitation of having only static functions (`swal.*`) that operate on the current modal is good for alerts (to avoid the temptation to stack them), but that is becoming a thing to reconsider now that we have toasts an maybe, nonmodal-modals like mentioned here.

Instead of `swal.*` function we would have (for example) classes like `SweetAlert2Alert`, `SweetAlert2Popup`, `SweetAlert2Toast`, each instance of them holding their state.
Alerts could only be displayed one at the same time, while toasts would position relatively to the other toasts, and popups (nonmodal-modals) could be positioned freely.

Being limited to only one modal at a time is already a problem with toasts (but the feature outweights that issue), but with nonmodal-modals, this is an unfortunate limitation.

My suggestion would be to delay the implementation of (officially supported) modal-nonmodals, and start to think about an API & internal engine refactor at mid/long-term. By the meantime, we could still add a little flag to unlock the possibility, now that the modal don't depend on the backdrop anymore.

Another limitation I see in the current API that would make nonmodal-modals painful to use: `text` or `html` options are enough when dealing with alerts. But I don't see myself creating such popups with a gigantic `html` string :)
