### ISSUE TITLE
SweetAlert 1 has continued Development

### ISSUE THREAD

**Issue by samturrell** [limonte/sweetalert2#709]
Hey @limonte - not sure if you noticed that https://github.com/t4t5/sweetalert is back in active development with many similar functions. Any worries?

**Comment by limonte** [comment]
Hi @samturrell! Yeah, I noticed some activity there, but I still can't apply the "active development" term to that repo. No worries from my side, now SweetAlert and SweetAlert2 are completely different projects. SweetAlert still struggling with its main issue - poor Community support.

**Comment by samturrell** [comment]
Good to hear, figured it would be worth bringing to your attention either way.

**Comment by toverux** [comment]
Just a few people had committed, mainly on docs, packaging, other chore tasks, plus a TypeScript rewrite... nothing had really changed, except the latest commit date.

**Comment by tripflex** [comment]
Yeah when looking at this I was confused by both repos, mainly because on this repo README you link to the original sweetalert page showing the changes from v1 to v2 .... but you still have maintained some of the previous attributes/settings from v1 in sweetalert2

For instance, in SweetAlert (version 2), `type` is no longer used it is now `icon` ...but in your repo (SweetAlert2) ... you still use `type` ... so why link to changes from v1 to v2 on the original SweetAlert page?  Made it  very confusing ...
