### ISSUE TITLE
Input Validator does not work

### ISSUE THREAD

**Issue by felix2ch** [limonte/sweetalert2#717]
Check it on 
https://limonte.github.io/sweetalert2 , 
all of it.

**Comment by toverux** [comment]
It's due to the release of SweetAlert v.7 which has changed the way you handle confirm and cancel (and other forms of dismissals).

The documentation isn't up to date (yet).

If you want to use an input with SweetAlert2 v.7, you can do this instead:

```js
const {dismiss, value: favoriteColor} = await swal({text: 'What is your favorite color?', input: text})
if (dismiss) {
  swal('I did not get your favorite color because "${dismiss}".')
} else {
  swal(`Your favorite color is "${favoriteColor}".`)
}
```

The reason is that promises returned by Swal are no longer rejected for dismissals, so it's easier to distinguish between normal conditions and technical, "fatal" errors (#485 for more).
Instead, it's resolved with an object that is of format `{ dismiss: 'reason' }` or `{ value: 'value' }`.

**Comment by limonte** [comment]
Should be fixed now, thanks for reporting @felix2ch
