### ISSUE TITLE
Cancel not working in 7.0.0

### ISSUE THREAD

**Issue by J000S** [limonte/sweetalert2#724]
Hi,

i've just updated from 6.11.4 to 7.0.0. I now have the problem, that cancelling the dialog will actually confirm the dialog :(
`swal({
								title: 'title',
								text: 'text',
							  	type: 'warning',
							  	showCancelButton: true,
							  	allowEnterKey: false,
							  	reverseButtons: true,
							  	cancelButtonText: 'cancelbText',
							  	confirmButtonText: 'confirmbText',
							  	buttonsStyling:false,
							  	confirmButtonClass: 'winkhaus-button',
							  	cancelButtonClass: 'winkhaus-button',
							  	focusConfirm: false,
							  	allowOutsideClick: false
							}).then(function () {...`

This happens in every swal i have.

**Comment by limonte** [comment]
Hello @J000S and thanks for reporting this issue!

First of all, I would like to pay your attention that you are doing upgrade to new **major** release. 
MAJOR versions, accordingly to [semver](http://semver.org/) always have **incompatible** API changes.

Before updrading you should always take a look on the RELEASE NOTES of the new major release: https://github.com/limonte/sweetalert2/releases/tag/v7.0.0

Before you were handling dismissals in the rejection handler: [[JSFIDDLE ↗]](https://jsfiddle.net/ad3quksn/198/)

```js
swal({
  ...
}).then(
  value => {
    // handle confirm
  },
  dismiss => {
    // handle dismiss
  }
}
```

Now you should handle both confirmations and dismissals in the fulfillment handler: [[JSFIDDLE ↗]](https://jsfiddle.net/ad3quksn/199/)
```js
swal({
  ...
}).then(result => {
  if (result.value) {
    // handle confirm
    console.log(result.value)
  } else {
    // handle dismiss, result.dismiss can be 'cancel', 'overlay', 'close', and 'timer'
    console.log(result.dismiss)
  }
})
```

In order to have painless backward compatibility with previous versions, use `useRejections: true` [[JSFIDDLE ↗]](https://jsfiddle.net/ad3quksn/200/)

```js
swal({
  useRejections: true           // <<<<<<------- BACKWARD COMPATIBILITY WITH v6.x
}).then(
  value => {
    // handle confirm
  },
  dismiss => {
    // handle dismiss
  }
}
```

:warning: `useRejections` is deprecated and will be removed in the next major release.

---

Why this was changed to this you can read here: https://github.com/limonte/sweetalert2/issues/485#issuecomment-338082080
