### ISSUE TITLE
Arrow function not working on IE11

### ISSUE THREAD

**Issue by Macfly60** [limonte/sweetalert2#764]
Hi,

You should change the JS code on the examples page, especially the one showing the use of the 'dismiss' parameter
Indeed, the arrow functions are not supported by IE11, which makes the whole page inoperable on this browser

**Comment by limonte** [comment]
Hi @Macfly60 

The plugin works in IE11, you can ensure that with this jsfiddle: https://jsfiddle.net/ad3quksn/250/

The examples page doesn't work with IE11, the reason is that we want to demonstrate how to use the plugin in a modern way. Read more about the reasoning: https://github.com/limonte/sweetalert2/issues/711#issuecomment-344089223

**Comment by limonte** [comment]
https://sweetalert2.github.io/ is now working for IE11 :tada:
