### ISSUE TITLE
Allow outside clicks always, except when modal is in the loading state

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#782]
There's an interesting question on SO: https://stackoverflow.com/q/47925036/1331425

After some thinking I would like to propose the non-breaking change: 

Convert the `allowOutsideClick` from boolean to:

```js
allowOutsideClick?: 'always' | 'when-not-loading' | false;
```

`'when-not-loading'` looks ugly for me though, I would like to come up with the nicer parameter. Ideas are welcome.

@angrykoala will this solution be acceptable for you?

Opinions from collaborators and the community are welcome!

**Comment by zenflow** [comment]
There are likely cases where someone is passing `allowOutsideClick: true`, for example (1) to override the defaults set with `swal.setDefaults`, or (2) because `true` is the result of an expression. So if we are to go the proposed route, I might suggest changing the type to something like `allowOutsideClick?: true | 'when-not-loading' | false;`. This would make the change fully backwards compatible; no need for [a warning](https://github.com/limonte/sweetalert2/pull/783/files#diff-1957cf081e6f36591195eae3cf092341R734) or an eventual breaking change (when the next major is released), and it wouldn't immediately break type-checking in projects that have it. We could think of a simple `true` as an unqualified affirmative, a.k.a. "always".

---

Another route we could go, which would eliminate the ugliness of `'when-not-loading'` and could serve a broader use-case: 

1. For `allowOutsideClick`, accept a boolean **or** a function with no args that returns a boolean (I think the type would look something like `allowOutsideClick?: boolean | () => boolean`)
2. Add a getter method to expose the "loading" state, i.e. `swal.isLoading()`
3. Possibly add more getter methods, exposing other bits of state, particularly `swal.isValidating()` since it's pretty similar.

This way for @angrykoala's use-case we would simply pass `allowOutsideClick: () => !swal.isLoading()`. Or for basically the same case, but when we also have an async inputValidator, `allowOutsideClick: () => !swal.isValidating && !swal.isLoading()`.

**Comment by zenflow** [comment]
I can make the PR if we go the allowOutsideClick-as-a-function route

**Comment by angrykoala** [comment]
why not a method to change the allowOutsideClick to be set? similar to `showValidationError` in the example?

would that be feasible?, if not I feel the second idea from @zenflow would be better than using string

thanks for your help

**Comment by limonte** [comment]
> For allowOutsideClick, accept a boolean or a function with no args that returns a boolean (I think the type would look something like allowOutsideClick?: boolean | () => boolean)
> Add a getter method to expose the "loading" state, i.e. swal.isLoading()
> Possibly add more getter methods, exposing other bits of state, particularly swal.isValidating() since it's pretty similar.

Perfect! :+1: :+1: :+1: 

> why not a method to change the allowOutsideClick to be set? similar to showValidationError in the example?

It's not possible to change params after popup initialization.

>  if not I feel the second idea from @zenflow would be better than using string

Yeah, I like it more as well. It'll provide a flexibility for future needs.

@zenflow please go ahead with the PR :rocket: Many thanks, you're making this plugin better!

Happy holidays everyone! :gift: :gift: :gift:

**Comment by limonte** [comment]
https://jsfiddle.net/limon/k6vm7y5o/ :tada:
